version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - retailnetwork

  retailstore:
    build: .
    container_name: retailstore
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RetailStoreDB;User=sa;Password=Your_password123;TrustServerCertificate=true;Encrypt=False;
    ports:
      - "5000:80"
    networks:
      - retailnetwork

networks:
  retailnetwork:
    driver: bridge